name: Makefile CI

on:
  push:
  pull_request:
    branches: [ "master" ]
  schedule:
    # Correr a medianoche (UTC?) todos los días
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt-get install texlive-full

    - name: Build
      run: make
